
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author doujones
 */
public class MainForm extends javax.swing.JFrame {

    // class level references
    DefaultTableModel tblModel = new DefaultTableModel();

    /* Creates new form MainForm
     */
    public MainForm() {
        initComponents();

        // Center the form
        this.setLocationRelativeTo(null);

        String[] colTitles = {"Name", "Address", "Type", "Length", "Width", "Cost"};
        tblModel.setColumnIdentifiers(colTitles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        lblCustomerAddress = new javax.swing.JLabel();
        txtFlooringType = new javax.swing.JTextField();
        lblFlooringType = new javax.swing.JLabel();
        txtFloorWidth = new javax.swing.JTextField();
        lblFloorWidth = new javax.swing.JLabel();
        txtFloorLength = new javax.swing.JTextField();
        lblFloorLength = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        scrFlooringOrders = new javax.swing.JScrollPane();
        tblFlooringOrders = new javax.swing.JTable();
        lblFloorCost = new javax.swing.JLabel();
        txtFloorCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerName.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblCustomerName.setText("Customer Name: ");

        txtCustomerName.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        txtCustomerAddress.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        lblCustomerAddress.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblCustomerAddress.setText("Customer Address: ");

        txtFlooringType.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        lblFlooringType.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblFlooringType.setText("Flooring Type: ");

        txtFloorWidth.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        lblFloorWidth.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblFloorWidth.setText("Floor Width: ");

        txtFloorLength.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        lblFloorLength.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblFloorLength.setText("Floor Length: ");

        btnDisplay.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        btnDisplay.setText("Display Records");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        btnAdd.setText("Add Record");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblFlooringOrders.setModel(tblModel);
        scrFlooringOrders.setViewportView(tblFlooringOrders);

        lblFloorCost.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        lblFloorCost.setText("Flooring Cost:");

        txtFloorCost.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrFlooringOrders, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCustomerName)
                                    .addComponent(lblFlooringType)
                                    .addComponent(lblFloorWidth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFlooringType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFloorWidth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFloorLength, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFloorCost, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFloorLength)
                                    .addComponent(txtFloorCost, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(260, 260, 260)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerAddress)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlooringType)
                    .addComponent(txtFlooringType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFloorWidth)
                    .addComponent(txtFloorWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFloorLength)
                    .addComponent(txtFloorLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFloorCost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFloorCost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDisplay))
                .addGap(42, 42, 42)
                .addComponent(scrFlooringOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // get info and build Order object
        String name = txtCustomerName.getText();
        String address = txtCustomerAddress.getText();
        String type = txtFlooringType.getText();
        double length = Double.parseDouble(txtFloorLength.getText());
        double width = Double.parseDouble(txtFloorWidth.getText());
        String costInput = txtFloorCost.getText();
        costInput = costInput.replace(",", "");
        costInput = costInput.replace("$", "");
        double cost = Double.parseDouble(costInput);

        Order customerOrder = new Order(name, address, type, length, width, cost);

        OrderDB data = new OrderDB();

        try {
            data.add(customerOrder);
            JOptionPane.showMessageDialog(this, "Order was written to the database");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        //get and display records from the database
        OrderDB data = new OrderDB();
        try {
            DecimalFormat currency = new DecimalFormat("$#, ##0.00");
            ArrayList<Order> list = data.getAll();
            
            for(int i = 0; i < list.size(); i++)
            {
                Order custOrder = list.get(i);
                Object[] row = {custOrder.getCustomerName(),
                custOrder.getCustomerAddress(), custOrder.getFlooringType(),
                custOrder.getFloorLength(), custOrder.getFloorWidth(),
                currency.format(custOrder.getFloorCost())
                };
                tblModel.addRow(row);
            }
        
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblFloorCost;
    private javax.swing.JLabel lblFloorLength;
    private javax.swing.JLabel lblFloorWidth;
    private javax.swing.JLabel lblFlooringType;
    private javax.swing.JScrollPane scrFlooringOrders;
    private javax.swing.JTable tblFlooringOrders;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtFloorCost;
    private javax.swing.JTextField txtFloorLength;
    private javax.swing.JTextField txtFloorWidth;
    private javax.swing.JTextField txtFlooringType;
    // End of variables declaration//GEN-END:variables
}
